name: Environment Variable Example

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Déclaration des variables d'environnement
    env:
      MESSAGE: "Déploiement réussi"

    steps:
      - name: Print deployment message
        run: echo "$MESSAGE"
        
# - name: Print a local env variable
#   env:
#     MESSAGE: "Déploiement réussi"
#   run: echo "$MESSAGE"
